# Generated by Django 5.2.8 on 2025-11-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.CharField(),
        ),
    ]
